# fly.toml app configuration file generated for summit-momotetsu on 2026-04-25T22:09:58+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'summit-momotetsu'
primary_region = 'nrt'
kill_signal = 'SIGTERM'
kill_timeout = '30s'

[build]
  dockerfile = 'Dockerfile'

[deploy]
  strategy = 'immediate'
  release_command = 'pnpm drizzle-kit migrate'

[env]
  NODE_ENV = 'production'
  TZ = 'Asia/Tokyo'

[processes]
  app = 'node dist/index.js'

[[vm]]
  size = 'shared-cpu-1x'
  memory = '256mb'
